//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConaviWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConaviWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] AC0_SAT {
            get {
                object obj = ResourceManager.GetObject("AC0_SAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] AC1_SAT {
            get {
                object obj = ResourceManager.GetObject("AC1_SAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] AC2_SAT {
            get {
                object obj = ResourceManager.GetObject("AC2_SAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] AC3_SAT {
            get {
                object obj = ResourceManager.GetObject("AC3_SAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] AC4_SAT {
            get {
                object obj = ResourceManager.GetObject("AC4_SAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] AC5_SAT {
            get {
                object obj = ResourceManager.GetObject("AC5_SAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ARC0_IES {
            get {
                object obj = ResourceManager.GetObject("ARC0_IES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ARC1_IES {
            get {
                object obj = ResourceManager.GetObject("ARC1_IES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ARC2_IES {
            get {
                object obj = ResourceManager.GetObject("ARC2_IES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ARC3_IES {
            get {
                object obj = ResourceManager.GetObject("ARC3_IES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ARC4_IES {
            get {
                object obj = ResourceManager.GetObject("ARC4_IES", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;2.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:cfd=&quot;http://www.sat.gob.mx/cfd/2&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:fn=&quot;http://schemas.microsoft.com/VisualStudio/2005/xpath-functions&quot;&gt;
        ///
        ///&lt;!-- Con el siguiente método se establece que la salida deberá ser en texto --&gt;
        ///
        ///  &lt;xsl:output version=&quot;1.0&quot; indent=&quot;no&quot; encoding=&quot;Utf-8&quot; method=&quot;text&quot;/&gt;
        ///
        ///  &lt;xsl:include href=&quot;http [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string fea_archivo_convenio {
            get {
                return ResourceManager.GetString("fea_archivo_convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;2.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:cfd=&quot;http://www.sat.gob.mx/cfd/2&quot; xmlns:fo=&quot;http://www.w3.org/1999/XSL/Format&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:fn=&quot;http://schemas.microsoft.com/VisualStudio/2005/xpath-functions&quot;&gt;
        ///
        ///&lt;!-- Con el siguiente método se establece que la salida deberá ser en texto --&gt;
        ///
        ///  &lt;xsl:output version=&quot;1.0&quot; indent=&quot;no&quot; encoding=&quot;Utf-8&quot; method=&quot;text&quot;/&gt;
        ///
        ///  &lt;xsl:include href=&quot;http [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string fea_convenio {
            get {
                return ResourceManager.GetString("fea_convenio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ocsp_ac0_sat {
            get {
                object obj = ResourceManager.GetObject("ocsp_ac0_sat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ocsp_ac1_sat {
            get {
                object obj = ResourceManager.GetObject("ocsp_ac1_sat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ocsp_ac2_sat {
            get {
                object obj = ResourceManager.GetObject("ocsp_ac2_sat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ocsp_ac3_sat {
            get {
                object obj = ResourceManager.GetObject("ocsp_ac3_sat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ocsp_ac4_sat {
            get {
                object obj = ResourceManager.GetObject("ocsp_ac4_sat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] ocsp_ac5_sat {
            get {
                object obj = ResourceManager.GetObject("ocsp_ac5_sat", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
