using System;
using ConaviWeb.Model;
using ConaviWeb.Model.Expedientes;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConaviWeb.Data.Expedientes
{
    public interface IExpedienteRepository
    {
        Task<int> GetIdUserArea(string area);
        Task<Inventario> GetInventarioTP(string area);
        Task<Inventario> GetInventarioControl(string area);
        Task<Inventario> GetInventarioControlById(int id);
        Task<Inventario> GetInventarioBibliohemerografico(string area);
        Task<Inventario> GetInventarioBiblioById(int id);
        //Task<Inventario> GetInventarioNoExpedientable(string area);
        Task<IEnumerable<Catalogo>> GetCodigosExp();
        Task<IEnumerable<Catalogo>> GetTiposSoporte();
        Task<IEnumerable<Catalogo>> GetTiposDocumentales();
        Task<IEnumerable<SerieDocumental>> GetSeries();
        Task<SerieDocumental> GetSerieDocumental(int id);
        Task<bool> UpdateSerieDocCat(SerieDocumental serie);
        Task<bool> ActivarSerieDocCat(int id);
        Task<bool> DesactivarSerieDocCat(int id);
        Task<IEnumerable<Catalogo>> GetAreas();
        Task<bool> InsertInventarioTP(Inventario inventario);
        //Task<bool> InsertExpedienteInventarioTP(Expediente expediente);
        //Task<bool> InsertCaratulaExpedienteTP(Caratula caratula);
        Task<IEnumerable<Expediente>> GetExpedientesInventarioTP(int id, int id_inventario);
        Task<IEnumerable<Expediente>> GetExpedientesTPByIdInv(int id);
        //Task<Expediente> GetExpedienteTP(int id);
        Task<Caratula> GetCaratulaExpedienteTP(int id, int legajo);
        //Task<bool> DropExpediente(int id);
        Task<bool> InsertInventarioControl(Inventario inventario);
        Task<bool> InsertExpedienteInventarioControl(Expediente expediente);
        Task<bool> UpdateExpedienteInventarioControl(Expediente expediente);
        Task<bool> InsertCaratulaExpedienteIC(Caratula caratula);
        Task<IEnumerable<Expediente>> GetExpedientesInventarioControl(int id, int id_inventario);
        Task<IEnumerable<Expediente>> GetExpedientesInventarioControlByIdInv(int id);
        Task<IEnumerable<Expediente>> GetExpedientesValidacionInventarioControl(int id_area);
        Task<Expediente> GetExpedienteControl(int id);
        Task<Caratula> GetCaratulaExpedienteControl(int id, int legajo, int idUser);
        Task<bool> DropExpedienteControl(int id);
        Task<bool> SendValExpedienteControl(int id);
        Task<bool> VoBoExpedienteControl(int id);
        Task<bool> RevalidacionExpedienteControl(int id, string obs);
        Task<int> sePuedeMigrarExpediente(int id, int tipo);
        Task<bool> MigrarExpedienteInvTP(int id);
        Task<bool> MigrarExpedienteInvNE(int id);
        Task<bool> InsertInventarioBibliohemerografico(Inventario inventario);
        Task<bool> InsertExpedienteBibliohemerografico(ExpedienteBibliohemerografico expediente);
        Task<IEnumerable<ExpedienteBibliohemerografico>> GetExpedientesBibliohemerograficos(int id, int id_inventario);
        Task<IEnumerable<ExpedienteBibliohemerografico>> GetExpedientesBibliohemerograficosByIdInv(int id);
        Task<ExpedienteBibliohemerografico> GetExpedienteBibliohemerografico(int id);
        Task<bool> UpdateExpedienteBibliohemerografico(ExpedienteBibliohemerografico expediente);
        Task<bool> DropExpedienteBibliohemerografico(int id);
        //Task<IEnumerable<ExpedienteBibliohemerografico>> GetExpedientesValidacionBiblio(int idArea);
        //Task<bool> SendValExpedienteBiblio(int id);
        //Task<bool> VoBoExpedienteBiblio(int id);
        //Task<bool> RevalidacionExpedienteBiblio(int id);
        Task<bool> InsertInventarioNoExpedientable(Inventario inventario);
        //Task<bool> InsertExpedienteNoExpedientable(ExpedienteNoExpedientable expediente);
        //Task<bool> InsertCaratulaNoExpedientable(Caratula caratula);
        Task<IEnumerable<Expediente>> GetExpedientesNoExpedientables(int id, int id_inventario);
        Task<IEnumerable<Expediente>> GetExpedientesNoExpedientablesByIdInv(int id);
        Task<Expediente> GetNoExpedientable(int id);
        Task<Caratula> GetCaratulaNoExpedientable(int id, int legajo);
        Task<IEnumerable<Area>> GetAreasLista();
        Task<bool> DropExpedienteNoExpedientable(int id);
        Task<bool> UpdateArea(Area area);
        Task<Area> GetArea(int id);
        Task<IEnumerable<Area>> GetAreaUser(int id);
        Task<bool> ActivarArea(int id);
        Task<bool> DesactivarArea(int id);
        Task<IEnumerable<Area>> GetPuestosLista();
        Task<IEnumerable<Area>> GetPuestosListaValidacion();
        Task<bool> UpdatePuesto(Area area);
        Task<int> GetIdUserPuesto(string puesto);
        Task<IEnumerable<Area>> GetPuestoUser(int id);
        Task<Area> GetPuesto(int id);
        Task<bool> ActivarPuesto(int id);
        Task<bool> DesactivarPuesto(int id);
        Task<IEnumerable<User>> GetUsuariosLista();
        Task<bool> UpdateUsuario(User usuario);
        Task<User> GetUsuario(int id);
        Task<bool> ActivarUsuario(int id);
        Task<bool> DesactivarUsuario(int id);
    }
}